# Build the dotnet.core app
build:
  - image: microsoft/dotnet:2.0-sdk
    workdir: /build
    environment:
      - PRODUCT_NAME=Deluxe.One.Nats
      - PRODUCT_VERSION=0.1.3
      - NUGET_HOST=http://nuget.service.owf-dev:5000
      - NUGET_KEY=8d8dc87c-b145-4591-9a2b-e377e0f93aa0
    commands: 
      - dotnet restore -r debian.8-x64 /build/csharp/$PRODUCT_NAME.csproj -s https://api.nuget.org/v3/index.json
      - dotnet pack -c Release /build/csharp/$PRODUCT_NAME.csproj --version-suffix $PRODUCT_VERSION -o /build/artifacts
      - dotnet nuget push /build/artifacts/$PRODUCT_NAME.$PRODUCT_VERSION.nupkg -k $NUGET_KEY -s $NUGET_HOST || true